#!/usr/bin/env bash

echo "------------------ adding manual -------------------------------------------------------------"
GH_PAGES_DIR=$(mktemp -d)
git clone --single-branch -b gh-pages --depth 1 git@github.com:${TRAVIS_REPO_SLUG}.git ${GH_PAGES_DIR}
mkdir -p ${GH_PAGES_DIR}/articles
cp -f ${TRAVIS_BUILD_DIR}/inst/doc/manual.pdf ${GH_PAGES_DIR}/articles/
cd ${GH_PAGES_DIR}
git add articles/manual.pdf
git commit -m 'added manual'
git push origin gh-pages
